---
- name: Install Nexus Repository OSS
  hosts: nexus_servers
  become: yes
  vars:
    nexus_version: '3.30.0-01'
    nexus_user: nexus
    nexus_group: nexus
    nexus_home: /opt/nexus
    nexus_data: /opt/sonatype-work
    nexus_download_url: "https://download.sonatype.com/nexus/3/nexus-{{ nexus_version }}-unix.tar.gz"

  tasks:
    - name: Install Java OpenJDK 11
      apt:
        name: openjdk-11-jdk
        state: present
        update_cache: yes

    - name: Create Nexus User
      user:
        name: "{{ nexus_user }}"
        comment: "Nexus Repository User"
        system: yes
        create_home: false

    - name: Create required directories
      file:
        path: "{{ item }}"
        state: directory
        owner: "{{ nexus_user }}"
        group: "{{ nexus_group }}"
      loop:
        - "{{ nexus_home }}"
        - "{{ nexus_data }}"

    - name: Download Nexus Repository OSS
      get_url:
        url: "{{ nexus_download_url }}"
        dest: "/tmp/nexus.tar.gz"
        mode: '0644'

    - name: Extract Nexus Repository OSS
      unarchive:
        src: "/tmp/nexus.tar.gz"
        dest: "{{ nexus_home }}"
        remote_src: yes
        extra_opts: [--strip-components=1]
        owner: "{{ nexus_user }}"
        group: "{{ nexus_group }}"

    - name: Configure Nexus as a service
      template:
        src: nexus.service.j2
        dest: /etc/systemd/system/nexus.service
      notify: Reload systemd and start nexus

    - name: Set Nexus to start on boot
      systemd:
        name: nexus
        enabled: yes
        state: started

  handlers:
    - name: Reload systemd and start nexus
      systemd:
        daemon_reload: yes
        name: nexus
        state: started
        enabled: yes
